### ISSUE TITLE
[BUG]: No module named 'numpy.typing'

### ISSUE THREAD

**Issue by remia** [colour-science/colour#946]
### Description

First, congrats for the amazing new release!

I had a small issue upgrading from pip using my current `numpy` version (1.19.4):
```
>>> import colour
Traceback (most recent call last):
  File "<input>", line 1, in <module>
    import colour
  File "/usr/local/lib/python3.9/site-packages/colour/__init__.py", line 50, in <module>
    from .utilities.deprecation import ModuleAPI, build_API_changes
  File "/usr/local/lib/python3.9/site-packages/colour/utilities/__init__.py", line 5, in <module>
    from colour.hints import Any, Dict
  File "/usr/local/lib/python3.9/site-packages/colour/hints/__init__.py", line 13, in <module>
    import numpy.typing as npt
ModuleNotFoundError: No module named 'numpy.typing'
```

Should the numpy [requirement](https://github.com/colour-science/colour/blob/develop/pyproject.toml#L48) be bumped to a newer release (mosty likely 1.20+)?

**Comment by KelSolaar** [comment]
Hi @remia,

Thanks good catch, as it currently stands, the minimum requirement should be Numpy 1.21, with Numpy 1.20 you will get the following error:

> AttributeError: module 'numpy.typing' has no attribute '_NestedSequence'

I will try to patch the code so that it works with 1.19 anyway!
